#!/bin/bash
# generate asterisk core backtrace
set -ex

which gdb > /dev/null || sudo yum install gdb

for CORE in core.*
do
	gdb -se "asterisk" -ex "bt full" -ex "thread apply all bt" -batch -c $CORE > backtrace-${CORE}.txt 2>backtrace-${CORE}-errors.txt
	mv $CORE processed-$CORE
	more backtrace-${CORE}.txt
done
