#!/bin/bash
# generate asterisk core backtrace
set -ex

for CORE in core.*
do
	gdb -se "asterisk" -ex "bt full" -ex "thread apply all bt" -batch -c $CORE > backtrace-$CORE 2>backtrace-$CORE-errors
	rm $CORE
	more backtrace-$CORE
done
