#!/bin/sh
# Build asterisk (download, compile, install) with many options

# this script does _not_ check to see if you have the necessary packages installed
# need: yum install -y make wget openssl-devel ncurses-devel  newt-devel libxml2-devel kernel-devel gcc gcc-c++ sqlite-devel libuuid-devel gtk2-devel

ASKINSTALL=true
INSTALL=false
VERDEST=false
DONTOPT=true

while [ "${1:0:1}" == "-" ]
do
	case "$1" in
	-i*)
		# go ahead and install too
		TO=${1:2}
		shift
		INSTALL=true
		ASKINSTALL=false
		if [ ! -z "$TO" ]
		then
			if [ "${TO:0:1}" = "/" ]
			then
				export INSTALL_PATH="$TO"
			else
				export INSTALL_PATH="$PWD/$TO"
			fi
		fi
		;;
	-n)
		# do not install and do not ask
		shift
		INSTALL=false
		ASKINSTALL=false
		;;
	-v)
		# dest dir is version only - no suffix
		shift
		VERDEST=true
		;;
	-o)
		# optimize (default is don't optimize)
		shift
		DONTOPT=false
		;;
	*)
		echo "ERROR: unknown argument: $1"
		exit 1
	esac
done


VERSIONS=(
	'1.4'
	'1.6.2'
	'1.8'
	'10'
	'11'
	'12'
	'trunk'
)

[ -d ~/src/origsvn/asterisk/branches ] && VERSIONS=(`ls ~/src/origsvn/asterisk/branches` 'trunk')

VERSION="$1"
if [ -z "$VERSION" ]
then
	COUNT=1
	for OPT in ${VERSIONS[*]}
	do
		echo "$COUNT: $OPT"
		COUNT=`expr $COUNT + 1`
	done

	echo ""
	echo -n "Select branch to install or enter version: "
	read SEL
	[ -z "$SEL" ] && echo "ERROR: no entry" && exit 1
	SEL=`expr $SEL - 1`
	VERSION="${VERSIONS[$SEL]}"
	[ -z "$VERSION" ] && VERSION="$SEL"
fi

#DEST="$VERSION-`date '+%F-%H-%M'`"
DEST="$VERSION"

# is that version in the list?
FOUND=0
for OPT in ${VERSIONS[*]}
do
	if [ "$VERSION" = "$OPT" ]
	then
		FOUND=1
	fi
done

if [ $FOUND -eq 0 ]
then
	# is it testsuite?
	if [ "$VERSION" = "testsuite" ]
	then
		[ -d testsuite ] && echo "ERROR: testsuite directory already exists" && exit 1
		if [ -f ~/.subversion/Digium_SVN-cacert-sha1.pem ]
		then
			svn co https://origsvn.digium.com/svn/testsuite/asterisk/trunk testsuite
		else
			svn co http://svn.asterisk.org/svn/testsuite/asterisk/trunk testsuite
		fi
		exit 0
	fi

	if ! $VERDEST
	then
		DEST="$VERSION-release"
	fi

	# try to download exact version
	wget -O /tmp/asterisk-$VERSION.tgz http://downloads.asterisk.org/pub/telephony/asterisk/releases/asterisk-$VERSION.tar.gz
	if [ $? -ne 0 ]
	then
		rm /tmp/asterisk-$VERSION.tgz
		echo "ERROR: Unable to download $VERSION"
		exit 1
	fi
	tar xvfz /tmp/asterisk-$VERSION.tgz
	if [ ! -d asterisk-$VERSION ]
	then
		echo "ERROR: after tar extraction, directory asterisk-$VERSION not found"
		exit 1
	fi
	mv asterisk-$VERSION $DEST
else
	# get matching branch from svn
	VERSIONPATH="$VERSION"
	[ "$VERSION" != "trunk" ] && VERSIONPATH="branches/$VERSION"
	FULLPATH="svn/asterisk/$VERSIONPATH"
	SVNURL="http://svn.asterisk.org/$FULLPATH"
	if [ -f ~/.subversion/Digium_SVN-cacert-sha1.pem ]
	then
		# user has digium svn access
		SVNURL="https://origsvn.digium.com/$FULLPATH"
	fi

	# get the revision number
	REVISION="`svn info $SVNURL |fgrep Revision:`"
	[ -z "$REVISION" ] && echo "ERROR: unable to obtain svn revision number?" && exit 1
	REVNUM=${REVISION#*: }

	if ! $VERDEST
	then
		DEST="$VERSION-r$REVNUM"
	fi

	[ -d "$DEST" ] && echo "Destination directory $DEST already exists!?" && exit 1
	mkdir $DEST

	echo "Downloading Asterisk $VERSION to directory $DEST"
	svn co $SVNURL $DEST

fi
cd $DEST

# dev mode is requsted by testsuite - use by default
CONFOPTS="--enable-dev-mode"

# for 64bit use correct lib dir
[ `uname -m` = "x86_64" ] && CONFOPTS="$CONFOPTS --libdir=/usr/lib64"

./configure $CONFOPTS || exit $?

#make menuselect || exit $?
make menuselect.makeopts
if $DONTOPT
then
	echo "Enabling DONT_OPTIMIZE"
	menuselect/menuselect --enable DONT_OPTIMIZE menuselect.makeopts
fi

make || exit $?

if $ASKINSTALL 
then
    while echo -n "Install (y/n): " && read ANSWER
    do
    	if [ "$ANSWER" = "y" ]
    	then
            INSTALL=true
    		break
    	fi
    	if [ "$ANSWER" = "n" -o "$ANSWER" = "" ]
    	then
    		break
    	fi
    done
fi

if $INSTALL
then
	echo "INSTALL_PATH=$INSTALL_PATH"
	read BOGUS
	if [ -z "$INSTALL_PATH" ]
	then
		# presume that root installation is necessary using sudo
		sudo make uninstall 
		sudo make install
		[ ! -f /etc/asterisk/extensions.conf ] && sudo make samples
	else
		# installing locally - insure directory exists
		[ ! -d "$INSTALL_PATH" ] && mkdir -p "$INSTALL_PATH"
		[ ! -d "$INSTALL_PATH" ] && echo "ERROR: unable to craete INSTALL_PATH $INSTALL_PATH" && exit 1
		make install 

		if [ ! -f $INSTALL_PATH/etc/asterisk/extensions.conf ]
		then
			make samples
			# and fixup paths in asterisk.conf to match
			sed -i "s|=> /|=> $INSTALL_PATH/|" $INSTALL_PATH/etc/asterisk/
		fi
	fi
fi

echo "===> LEAVING BUILD DIRECTORY: `pwd`"
