#!/bin/sh
# fix xterm by installing terminus as the default font
# this works around issue with very slow redraw

# fix it only on this session by loading a dummy config
# this way any other instances that happen to share the
# same $HOME are not affected on reboot

# after running this, only newly spawned xterm's will be 'fixed'

echo 'xterm*faceName:Terminus:style=Regular:size=6' > /tmp/xres.$$

xrdb -merge /tmp/xres.$$

rm -f /tmp/xres.$$
