#!/bin/sh
# fix xterm by installing terminus as the default font
# this resolves issue where very slow redraw was occuring on xterm

# remove it if already there
grep '^xterm\*faceName' ~/.Xresources >/dev/null && sed -i '/^xterm\*faceName/d' ~/.Xresources

# add it
echo 'xterm*faceName:Terminus:style=Regular:size=6' >> ~/.Xresources

# load it
xrdb -merge ~/.Xresources
