#!/bin/sh
# fixes bug in ekiga where it doesn't see audio device
# see bug https://bugzilla.redhat.com/show_bug.cgi?id=666256

cd /usr/lib
ln -s ptlib-2.6.5 2.6.5
echo Restart ekiga and audio should now function
