#!/bin/bash
# asterisk testsuite - install needed dependancies
# need epel for PyYAML

set -x

if [ "$1" = "-u" ]
then
	sudo rm -rfv /usr/include/pj*
	sudo rm -rfv /usr/include/srtp
	sudo rm -rfv /usr/bin/sipp
	sudo rm -rfv /usr/bin/asttest
	sudo rm -rfv /usr/lib*/libsrtp*
	sudo rm -rfv /usr/lib*/libpj*
	sudo rm -rfv /usr/lib*/libjansson*
	sudo rm -rfv /usr/lib/python2.6/site-packages/pjsua*
	sudo rm -rfv /usr/lib/python2.6/site-packages/_pjsua*
	sudo rm -rfv /usr/lib/python2.6/site-packages/easy-install.pth
	sudo rm -rfv /usr/lib/python2.6/site-packages/starpy*
	sudo rm -rfv /usr/local/include/spandsp*
	sudo rm -rfv /usr/local/include/jansson*
	sudo rm -rfv /usr/local/bin/asttest
	sudo rm -rfv /usr/local/lib/libspandsp*
	sudo rm -rfv /usr/local/lib/libjansson*
	sudo rm -rfv /usr/bin/pjsua
	sudo rm -rfv /tmp/jansson*
	exit 0
fi

#TODO: fix this
#yum-epel

[ ! -d testsuite ] && ba testsuite
[ ! -d testsuite ] && echo "ERROR: testsuite not installed" && exit 1

[ ! -d testsuite/asttest -o ! -d testsuite/addons ] && echo "ERROR: testsuite missing asttest or addons" && exit 1


SYSLIBDIR=/usr/lib
[ "`uname -m`" = "x86_64" ] && SYSLIBDIR=/usr/lib64

# not centos
[ ! -f /etc/redhat-release ] && sudo apt-get -y install python2.7-dev libncurses-dev libz-dev libssl-dev libxml2-dev libsqlite3-dev uuid-dev uuid libspeex-dev libspeexdsp-dev libogg-dev libvorbis-dev libasound2-dev portaudio19-dev libcurl4-openssl-dev libpq-dev unixodbc-dev libsqlite0-dev libmysqlclient15-dev libneon27-dev libgmime-2.6-dev libusb-dev liblua5.1-0-dev lua5.1 libopenh323-dev libvpb-dev libgtk2.0-dev libmysqlclient-dev libbluetooth-dev libradiusclient-ng-dev freetds-dev libsnmp-dev libiksemel-dev libcorosync-dev libnewt-dev libpopt-dev libedit-dev doxygen libjansson-dev libldap-dev subversion git libxslt1-dev libpcap0.8-dev libtiff-dev gawk

# centos
[ -f /etc/redhat-release ] && sudo apt-get -y install automake PyYAML libpcap-devel gcc-objc python-devel python-twisted git subversion libtiff-devel make wget openssl-devel ncurses-devel newt-devel libxml2-devel kernel-devel gcc gcc-c++ sqlite-devel libuuid-devel gtk2-devel gmime-devel gmime22-devel patch python-setuptools unixODBC-devel libcurl-devel libogg-devel libvorbis-devel speex-devel spandsp-devel freetds-devel net-snmp-devel iksemel-devel openais-devel popt-devel libtool-ltdl-devel libsqlite3x-devel radiusclient-ng-devel portaudio-devel postgresql-devel libresample-devel neon-devel libical-devel openldap-devel sqlite2-devel mysql-devel bluez-libs-devel jack-audio-connection-kit-devel Cython python-pip python-yaml

#testsuite/contrib/scripts/install_prereq install

# need python construct from pip
[ ! -d /usr/lib/python2.6/site-packages/construct ] && sudo pip install construct
[ ! -d /usr/lib/python2.6/site-packages/requests ] && sudo pip install requests
[ ! -d /usr/lib/python2.6/site-packages/autobahn ] && sudo pip install autobahn

mkdir testsuite-support
cd testsuite-support

# yappcap Installation

#git clone https://github.com/otherwiseguy/yappcap
#[ $? -ne 0 ] && echo "ERROR: git clone yappcap failed" && exit 1
#[ ! -d yappcap ] && echo "ERROR: target directory yappcap missing" && exit 1
#cd yappcap
#make
#[ $? -ne 0 ] && echo "ERROR: make yappcap failed" && exit 1
#sudo make install
#[ $? -ne 0 ] && echo "ERROR: make yappcap install failed" && exit 1
#cd ..

# SIPp Installation

# this is v3.1: http://sipp.sourceforge.net/snapshots/sipp.2009-07-29.tar.gz
wget -O sipp.tgz http://downloads.sourceforge.net/project/sipp/sipp/3.3/sipp-3.3.tar.gz
[ $? -ne 0 ] && exit $?

SIPP_DIR="sipp-3.3"

rm -rf $SIPP_DIR
[ $? -ne 0 ] && echo "ERROR: rm -rf $SIPP_DIR failed" && exit 1
tar xfz sipp.tgz
[ $? -ne 0 ] && echo "ERROR: tar extraction failed" && exit 1
[ ! -d $SIPP_DIR ] && echo "ERROR: tar extraction target missing" && exit 1
cd $SIPP_DIR
make pcapplay_ossl
[ $? -ne 0 ] && echo "ERROR: make pcapplay_ossl failed" && exit 1
sudo cp sipp /usr/bin

cd ..

# install PJPROJECT

rm -rf pjproject
git clone https://github.com/asterisk/pjproject pjproject
[ $? -ne 0 ] && echo "ERROR: svn co pjproject failed" && exit 1
cd pjproject
[ $? -ne 0 ] && echo "ERROR: cd to pjproject failed" && exit 1
./configure --prefix=/usr --enable-shared --disable-sound --disable-resample --disable-video --disable-opencore-amr --libdir=$SYSLIBDIR
make dep
[ $? -ne 0 ] && echo "ERROR: make dep pjproject failed" && exit 1
make
[ $? -ne 0 ] && echo "ERROR: make pjproject failed" && exit 1
sudo make install
sudo ldconfig
cd ..

# install PJSUA

rm -rf pjsua
[ $? -ne 0 -o -d pjsua ] && echo "ERROR: rm -rf pjsua failed" && exit 1
svn co http://svn.pjsip.org/repos/pjproject/trunk@4438 pjsua
[ $? -ne 0 ] && echo "ERROR: svn co pjsua failed" && exit 1
cd pjsua
[ $? -ne 0 ] && echo "ERROR: cd to pjsua failed" && exit 1

echo "#define PJ_HAS_IPV6 1" >pjlib/include/pj/config_site.h
# sandwichmaker-puppet doesn't do this...
#cat pjlib/include/pj/config_site_sample.h  >>pjlib/include/pj/config_site.h

#./configure CFLAGS=-fPIC
./configure CFLAGS=-fPIC --enable-shared --libdir=$SYSLIBDIR --with-external-srtp --with-external-speex --with-external-pa

make dep
[ $? -ne 0 ] && echo "ERROR: make pjsua def failed" && exit 1
make
[ $? -ne 0 ] && echo "ERROR: make pjsua failed" && exit 1
make -C pjsip-apps/build pjsua 
[ $? -ne 0 ] && echo "ERROR: make pjsua specifically failed" && exit 1
sudo make install
[ $? -ne 0 ] && echo "ERROR: make install pjsua failed" && exit 1

sudo cp -v pjsip-apps/bin/pjsua-`uname -m`-*-linux-gnu /usr/sbin/pjsua
[ $? -ne 0 ] && echo "ERROR: cp pjsua install failed" && exit 1
sudo make -C pjsip-apps/src/python install
[ $? -ne 0 ] && echo "ERROR: make pjsua python install failed" && exit 1

# some files left as root
sudo chown -R $USER.$USER .

# reinstall libraries with different configuration options (per puppet)
./configure --enable-shared --libdir=$SYSLIBDIR --with-external-srtp --with-external-speex --with-external-pa --disable-resample

make dep
[ $? -ne 0 ] && echo "ERROR: make dep pjsua2 failed" && exit 1
make
[ $? -ne 0 ] && echo "ERROR: make pjsua2 failed" && exit 1
sudo make install
[ $? -ne 0 ] && echo "ERROR: make install pjsua2 failed" && exit 1
sudo ldconfig


# some files left as root
sudo chown -R $USER.$USER .
cd ..

# install spandsp

wget -O spandsp.tgz http://soft-switch.org/downloads/spandsp/spandsp-0.0.6pre21.tgz
[ $? -ne 0 ] && exit $?
rm -rf spandsp-0.0.6
[ $? -ne 0 ] && echo "ERROR: rm -rf spandsp-0.0.6 failed" && exit 1
tar xvfz spandsp.tgz 
[ ! -d spandsp-0.0.6 ] && echo "ERROR: tarball directory spandsp-0.0.6 missing" && exit 1
cd spandsp-0.0.6
./configure
make
[ $? -ne 0 ] && echo "ERROR: make spandsp failed" && exit 1
sudo make install
[ $? -ne 0 ] && echo "ERROR: make spandsp install failed" && exit 1

cd ..


# install libsrtp

wget -O srtp.tgz http://srtp.sourceforge.net/srtp-1.4.2.tgz
rm -rf srtp
[ $? -ne 0 ] && echo "ERROR: rm -rf srtp failed" && exit 1
tar xvfz  srtp.tgz 
[ ! -d srtp ] && echo "ERROR: tarbal directory srtp missing" && exit 1
cd srtp
./configure CFLAGS=-fPIC --prefix=/usr
make
[ $? -ne 0 ] && echo "ERROR: make libsrtp failed" && exit 1
make runtest
[ $? -ne 0 ] && echo "ERROR: make libsrtp runtest failed" && exit 1
sudo make uninstall
sudo make install
[ $? -ne 0 ] && echo "ERROR: make libsrtp install failed" && exit 1

cd ..

# now at testsuite-support

cd ..

[ ! -d testsuite ] && echo "ERROR: path mixup need testsuite from `pwd`" && exit 1
cd testsuite

# now in testsuite root

# ASTTest installation
cd asttest
make
[ $? -ne 0 ] && echo "ERROR: make asttest failed" && exit 1
sudo make install
[ $? -ne 0 ] && echo "ERROR: make asttest install failed" && exit 1
# TestSuiteUtils.which() doesn't find it in /usr/local/bin...
[ -f /usr/local/bin/asttest ] && sudo cp /usr/local/bin/asttest /usr/bin
#asttest 2>/dev/null
#[ $? -ne 1 ] && echo "ERROR: failed asttest installation" && exit 1 

cd ..

# StarPY Installation

cd addons
make update
[ $? -ne 0 ] && echo "ERROR: make update failed" && exit 1
cd starpy
sudo python setup.py install
[ $? -ne 0 ] && echo "ERROR: python starpy setup.py install failed" && exit 1
sudo chown -R $USER.$USER .
cd ..
cd ..

# if libjansson not installed...
if [ ! -f /usr/local/lib/libjansson.so.4 ]
then
	wget -O /tmp/jansson-2.4.tar.gz http://www.digip.org/jansson/releases/jansson-2.4.tar.gz
	tar xvfz /tmp/jansson-2.4.tar.gz --no-same-owner
	(cd jansson-2.4; ./configure && make && sudo make install)
	[ $? -ne 0 ] && echo "ERROR: libjansson compile failed" && exit 1
fi

sudo cp /usr/local/lib/libjansson.so.4 $SYSLIBDIR
[ $? -ne 0 ] && echo "ERROR: libjansson install failed" && exit 1

echo ""
echo "*** Asterisk testsuite dependencies installed ***"
echo ""

