#!/bin/bash
# Install or update vim plugin syntastic
set -ex

# pip package is in epel on rhel based systems
[ -f /etc/redhat-release -a ! -f /etc/yum.repos.d/epel.repo ] && yum-epel

install-packages vim wget python-pip wget

# add some extra whitespace highlighting rules that I like
if ! fgrep 'highlight Tabs' ~/.vimrc > /dev/null
then
	cat <<---- >>~/.vimrc
highlight Tabs ctermbg=lightgray
let matchTabs = matchadd("Tabs","\t",-1)
highlight Tabspace ctermbg=Magenta
let matchTabspace = matchadd("Tabspace",'\t\zs \+',-1)
highlight Spacetab ctermbg=Red
let matchSpacetab = matchadd("Spacetab",' \+\ze\t',-1)
highlight Trailing ctermbg=red
let matchTrailing = matchadd("Trailing",'\s\+\$',-1)
highlight CommaSpace ctermbg=Yellow
let matchCommaSpace = matchadd("CommaSpace",',[^ ]',-1)
set modeline
---
fi

# install the plugin

mkdir -p ~/.vim/autoload ~/.vim/bundle

wget --no-check-certificate -O ~/.vim/autoload/pathogen.vim https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim

fgrep 'pathogen' ~/.vimrc >/dev/null || echo "execute pathogen#infect()" >> ~/.vimrc

cd ~/.vim/bundle
if [ -d syntastic ]
then
	cd syntastic
	git pull
else
	git clone https://github.com/scrooloose/syntastic.git
fi

# make sure various lints are installed
sudo pip install flake8
