#!/bin/sh
# asterisk testsuite - install needed dependancies
# need epel for PyYAML
yum-epel

[ ! -d testsuite ] && ba testsuite
[ ! -d testsuite ] && echo "ERROR: testsuite not installed" && exit 1

#[ `whoami` != 'root' ] && exec sudo $0

# assuming CentOS for now

sudo yum -y install automake PyYAML lua-devel libpcap-devel gcc-objc python-devel python-twisted subversion libtiff-devel make wget openssl-devel ncurses-devel newt-devel libxml2-devel kernel-devel gcc gcc-c++ sqlite-devel libuuid-devel gtk2-devel gmime-devel gmime22-devel patch python-setuptools unixODBC-devel libcurl-devel libogg-devel libvorbis-devel speex-devel spandsp-devel freetds-devel net-snmp-devel iksemel-devel openais-devel popt-devel libtool-ltdl-devel libsqlite3x-devel radiusclient-ng-devel portaudio-devel postgresql-devel libresample-devel neon-devel libical-devel openldap-devel sqlite2-devel mysql-devel bluez-libs-devel jack-audio-connection-kit-devel

#testsuite/contrib/scripts/install_prereq install

mkdir testsuite-support
cd testsuite-support

# SIPp Installation

# this is v3.1: http://sipp.sourceforge.net/snapshots/sipp.2009-07-29.tar.gz
wget -O sipp.tgz http://downloads.sourceforge.net/project/sipp/sipp/3.3/sipp-3.3.tar.gz
[ $? -ne 0 ] && exit $?

SIPP_DIR="sipp-3.3"

rm -rf $SIPP_DIR
[ $? -ne 0 ] && echo "ERROR: rm -rf $SIPP_DIR failed" && exit 1
tar xvfz sipp.tgz
[ $? -ne 0 ] && echo "ERROR: tar extraction failed" && exit 1
[ ! -d $SIPP_DIR ] && echo "ERROR: tar extraction target missing" && exit 1
cd $SIPP_DIR
make pcapplay_ossl
[ $? -ne 0 ] && echo "ERROR: make pcapplay_ossl failed" && exit 1
sudo cp sipp /usr/bin

cd ..


# install PJSUA

rm -rf pjproject
[ $? -ne 0 ] && echo "ERROR: rm -rf pjproject failed" && exit 1
svn co http://svn.pjsip.org/repos/pjproject/trunk pjproject
cd pjproject
./configure CFLAGS=-fPIC
echo "#define PJ_HAS_IPV6 1" >pjlib/include/pj/config_site.h
cat pjlib/include/pj/config_site_sample.h  >>pjlib/include/pj/config_site.h
make dep
[ $? -ne 0 ] && echo "ERROR: make pjproject def failed" && exit 1
make
[ $? -ne 0 ] && echo "ERROR: make pjproject failed" && exit 1
sudo cp pjsip-apps/bin/pjsua-x86_64-unknown-linux-gnu /usr/sbin/pjsua

sudo make -C pjsip-apps/src/python install
[ $? -ne 0 ] && echo "ERROR: make pjproject python install failed" && exit 1

# some files left as root
sudo chown -R $USER.$USER .
cd ..


# install spandsp

wget -O spandsp.tgz http://soft-switch.org/downloads/spandsp/spandsp-0.0.6pre21.tgz
[ $? -ne 0 ] && exit $?
rm -rf spandsp-0.0.6
[ $? -ne 0 ] && echo "ERROR: rm -rf spandsp-0.0.6 failed" && exit 1
tar xvfz spandsp.tgz 
[ ! -d spandsp-0.0.6 ] && echo "ERROR: tarball directory spandsp-0.0.6 missing" && exit 1
cd spandsp-0.0.6
./configure
make
[ $? -ne 0 ] && echo "ERROR: make spandsp failed" && exit 1
sudo make install
[ $? -ne 0 ] && echo "ERROR: make spandsp install failed" && exit 1

cd ..


# install libsrtp

wget -O srtp.tgz http://srtp.sourceforge.net/srtp-1.4.2.tgz
rm -rf srtp
[ $? -ne 0 ] && echo "ERROR: rm -rf srtp failed" && exit 1
tar xvfz  srtp.tgz 
[ ! -d srtp ] && echo "ERROR: tarbal directory srtp missing" && exit 1
cd srtp
./configure CFLAGS=-fPIC --prefix=/usr
make
[ $? -ne 0 ] && echo "ERROR: make libsrtp failed" && exit 1
make runtest
[ $? -ne 0 ] && echo "ERROR: make libsrtp runtest failed" && exit 1
sudo make uninstall >/dev/null 2>/dev/null
sudo make install
[ $? -ne 0 ] && echo "ERROR: make libsrtp install failed" && exit 1

cd ..

# now at testsuite-support

cd ..

[ ! -d testsuite ] && echo "ERROR: path mixup need testsuite from `pwd`" && exit 1
cd testsuite

# now in testsuite root

# ASTTest installation
cd asttest
make
[ $? -ne 0 ] && echo "ERROR: make asttest failed" && exit 1
sudo make install
[ $? -ne 0 ] && echo "ERROR: make asttest install failed" && exit 1
# TestSuiteUtils.which() doesn't find it in /usr/local/bin...
[ -f /usr/local/bin/asttest ] && sudo cp /usr/local/bin/asttest /usr/bin
#asttest 2>/dev/null
#[ $? -ne 1 ] && echo "ERROR: failed asttest installation" && exit 1 

cd ..

# StarPY Installation

cd addons
make update
[ $? -ne 0 ] && echo "ERROR: make update failed" && exit 1
cd starpy
sudo python setup.py install
[ $? -ne 0 ] && echo "ERROR: python starpy setup.py install failed" && exit 1
cd ..
cd ..

echo ""
echo "*** Configure asterisk with ./configure --enable-dev-mode and install ***"
echo ""
