#!/bin/sh
# install pjsip directly from teluu trunk

LIBDIR=/usr/lib
[ `uname -m` = "x86_64" ] && [ -d /usr/lib64 ] && LIBDIR="/usr/lib64"

set -ex
svn co http://svn.pjsip.org/repos/pjproject/trunk pjsip.$$
cd pjsip.$$
echo "#define PJ_HAS_IPV6 1" >pjlib/include/pj/config_site.h
./configure --enable-shared --libdir=$LIBDIR --with-external-srtp --with-external-speex --with-external-pa --disable-resample 
make dep 
make 
sudo make install 
sudo ldconfig
cd ..
sudo rm -rf pjsip.$$
