#!/bin/sh
# install pjsip directly from teluu trunk

install-packages git speex-devel/libspeex-dev libsrtp-devel/ portaudio-devel/

set -ex

LIBDIR=/usr/lib
[ `uname -m` = "x86_64" ] && [ -d /usr/lib64 ] && LIBDIR="/usr/lib64"

if [ "$1" = "-a" ]
then
	echo "Installing PJSIP from Asterisk Github"
	[ -d pjproject ] && rm -rf pjproject
	git clone https://github.com/asterisk/pjproject pjproject
	cd pjproject
	echo "#define PJ_HAS_IPV6 1" >pjlib/include/pj/config_site.h
	./configure --enable-shared --libdir=$LIBDIR --with-external-srtp --with-external-speex --with-external-pa --disable-resample 
	make dep 
	make 
	sudo make install 
	sudo ldconfig
	exit
fi

REVISION="`svn info http://svn.pjsip.org/repos/pjproject/trunk|fgrep Revision`"
REVNUM="${REVISION#*: }"
svn co http://svn.pjsip.org/repos/pjproject/trunk pjsip-r$REVNUM
cd pjsip-r$REVNUM
echo "#define PJ_HAS_IPV6 1" >pjlib/include/pj/config_site.h
./configure --enable-shared --libdir=$LIBDIR --with-external-srtp --with-external-speex --with-external-pa --disable-resample 
make dep 
make 
sudo make install 
sudo ldconfig
