#!/bin/bash -e
# install an arbitrary list of packages
#
# for example:
#   install-packages lynx ncurses-devel/ncurses-dev
#
# if two packages are given with a / separator,
# the left one is the redhat style package name, and
# the right one is the debian style package name
#
# if the package is already installed, no attempt to
# install or update is made

PKGS=""

if [ -f /etc/redhat-release ]
then
	for pkg in $*
	do
		rh="${pkg%/*}"
		[ -z "$rh" ] && continue
		rpm -q $rh >/dev/null || PKGS="$PKGS $rh"
	done
	if [ ! -z "$PKGS" ]
	then
		sudo yum -y install $PKGS
	fi
else
	for pkg in $*
	do
		deb="${pkg#*/}"
		[ -z "$deb" ] && continue
		dpkg-query -s "$deb" >/dev/null || PKGS="$PKGS $deb"
	done
	if [ ! -z "$PKGS" ]
	then
		sudo apt-get -y install $PKGS
	fi
fi
exit 0
