#!/bin/sh
# Upgrade FreePBX to SNG7

set -e

if ! which fwconsole >/dev/null
then
	echo "Error: is FreePBX installed?"
	exit 1
fi

[ `whoami` != 'root' ] && exec sudo $0

if [ ! -d /root/previous-yum.repos.d ]
then
	mkdir /root/previous-yum.repos.d
	mv  /etc/yum.repos.d/* /root/previous-yum.repos.d
fi

cat >/etc/yum.repos.d/CentOS-Sources.repo <<'::::::::::::::'
# CentOS-Sources.repo
#
# The mirror system uses the connecting IP address of the client and the
# update status of each mirror to pick mirrors that are updated to and
# geographically close to the client.  You should use this for CentOS updates
# unless you are manually picking other mirrors.
#
# If the mirrorlist= does not work for you, as a fall back you can try the 
# remarked out baseurl= line instead.
#
#

[centos-base-source]
name=CentOS-$releasever - Base Sources
baseurl=http://vault.centos.org/centos/$releasever/os/Source/
gpgcheck=1
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

#released updates 
[centos-updates-source]
name=CentOS-$releasever - Updates Sources
baseurl=http://vault.centos.org/centos/$releasever/updates/Source/
gpgcheck=1
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

#additional packages that may be useful
[centos-extras-source]
name=CentOS-$releasever - Extras Sources
baseurl=http://vault.centos.org/centos/$releasever/extras/Source/
gpgcheck=1
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

#additional packages that extend functionality of existing packages
[centos-centosplus-source]
name=CentOS-$releasever - Plus Sources
baseurl=http://vault.centos.org/centos/$releasever/centosplus/Source/
gpgcheck=1
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
::::::::::::::

cat >/etc/yum.repos.d/Sangoma-Base.repo <<'::::::::::::::'
# This is the standard Sangoma Yum Repository

[sng-base]
name=Sangoma-$releasever - Base
mirrorlist=http://mirrorlist.sangoma.net/?release=$releasever&arch=$basearch&repo=os&dist=$dist
#baseurl=http:/package1.sangoma.net/sng7/$releasever/os/$basearch/
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Sangoma-7

[sng-updates]
name=Sangoma-$releasever - Updates
mirrorlist=http://mirrorlist.sangoma.net/?release=$releasever&arch=$basearch&repo=updates&dist=$dist
#baseurl=http://package1.sangoma.net/sng7/$releasever/updates/$basearch/
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Sangoma-7

[sng-extras]
name=Sangoma-$releasever - Extras
mirrorlist=http://mirrorlist.sangoma.net/?release=$releasever&arch=$basearch&repo=extras&dist=$dist
#baseurl=http://package1.sangoma.net/sng7/$releasever/extras/$basearch/
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Sangoma-7

[sng-pkgs]
name=Sangoma-$releasever - Sangoma Open Source Packages
mirrorlist=http://mirrorlist.sangoma.net/?release=$releasever&arch=$basearch&repo=sng7&dist=$dist
#baseurl=http://package1.sangoma.net/sng7/$releasever/sng7/$basearch/
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Sangoma-7

[sng-epel]
name=Sangoma-$releasever - Sangoma Epel mirror
mirrorlist=http://mirrorlist.sangoma.net/?release=$releasever&arch=$basearch&repo=epel&dist=$dist
#baseurl=http://package1.sangoma.net/sng7/$releasever/epel/$basearch/
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7

::::::::::::::

cat >/etc/yum.repos.d/Sangoma-Commercial.repo <<'::::::::::::::'
[sng-commercial]
name=Sangoma-$releasever - Commercial Modules
mirrorlist=http://mirrorlist.sangoma.net/?release=$releasever&arch=$basearch&repo=commercial&dist=$dist
#baseurl=http:/package1.sangoma.net/sng7/$releasever/commercial/$basearch/
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Sangoma-7
enabled=0
::::::::::::::

cat >/etc/yum.repos.d/Sangoma-CR.repo <<'::::::::::::::'
# Sangoma-CR.repo
#
# The Continuous Release ( CR )  repository contains rpms that are due in the next
# release for a specific Sangoma Linux Version ( eg. next release in Sangoma-7 );
# these rpms are far less tested, with no integration checking or update path
# testing having taken place. They are still built from the upstream sources, but
# might not map to an exact upstream distro release.
#
# These packages are made available soon after they are built, for people willing 
# to test their environments, provide feedback on content for the next release, and
# for people looking for early-access to next release content.
#
# The CR repo is shipped in a disabled state by default; its important that users 
# understand the implications of turning this on. 
#
# NOTE: We do not use a mirrorlist for the CR repos, to ensure content is available
#       to everyone as soon as possible, and not need to wait for the external
#       mirror network to seed first. However, many local mirrors will carry CR repos
#       and if desired you can use one of these local mirrors by editing the baseurl
#       line in the repo config below.
#

[sng-cr]
name=Sangoma-$releasever - cr
baseurl=http://package1.sangoma.net/sng7/$releasever/cr/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
enabled=0
::::::::::::::

cat >/etc/yum.repos.d/Sangoma-fasttrack.repo <<'::::::::::::::'
[fasttrack]
name=Sangoma-7 - fasttrack
mirrorlist=http://mirrorlist.sangoma.net/?release=$releasever&arch=$basearch&repo=fasttrack&dist=$dist
#baseurl=http:/package1.sangoma.net/sng7/$releasever/fasttrack/$basearch/
gpgcheck=1
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

::::::::::::::

cat >/etc/yum.repos.d/Sangoma-Media.repo <<'::::::::::::::'
# Sangoma-Media.repo
#
#  This repo can be used with mounted DVD media, verify the mount point for
#  Sangoma-7.  You can use this repo and yum to install items directly off the
#  DVD ISO that we release.
#
# To use this repo, put in your DVD and use it with the other repos too:
#  yum --enablerepo=sng7-media [command]
#  
# or for ONLY the media repo, do this:
#
#  yum --disablerepo=\* --enablerepo=sng7-media [command]

[sng7-media]
name=Sangoma-$releasever - Media
baseurl=file:///media/Sangoma/
        file:///media/cdrom/
        file:///media/cdrecorder/
gpgcheck=0
enabled=0

::::::::::::::

cat >/etc/yum.repos.d/Sangoma-Sources.repo <<'::::::::::::::'
# Source RPM Repositories

[sng-src]
name=SRPMs for Sanoma specific packages
baseurl=http://package1.sangoma.net/src
gpgcheck=0
enabled=0

[sng-src-os]
name=SRPMs for Sanoma OS
baseurl=http://package1.sangoma.net/sng7/src/os
gpgcheck=0
enabled=0

[sng-src-updates]
name=SRPMs for Sanoma Updates
baseurl=http://package1.sangoma.net/sng7/src/updates
gpgcheck=0
enabled=0

[sng-src-epel]
name=SRPMs for Epel Packages
baseurl=http://package1.sangoma.net/sng7/src/epel
gpgcheck=0
enabled=0

::::::::::::::

while read PKG
do
	ALL="$ALL $PKG"
done <<::::::::::::::
GeoIP
ImageMagick
MySQL-python
OpenEXR-libs
SDL
acl
alsa-lib
apcupsd
apr
apr-util
asterisk-sounds-core-en-alaw
asterisk-sounds-core-en-ulaw
asterisk-sounds-core-en-wideband
asterisk-sounds-core-en_GB-ulaw
asterisk-sounds-core-es-ulaw
asterisk-sounds-core-fr-ulaw
asterisk-sounds-core-it-ulaw
asterisk-sounds-core-ja-ulaw
asterisk-sounds-extra-en-alaw
asterisk-sounds-extra-en-ulaw
asterisk-sounds-extra-en-wideband
asterisk-sounds-moh-opsound-alaw
asterisk-sounds-moh-opsound-sln
asterisk-version-switch
asterisk13
asterisk13-addons
asterisk13-addons-bluetooth
asterisk13-addons-core
asterisk13-addons-mysql
asterisk13-addons-ooh323
asterisk13-core
asterisk13-curl
asterisk13-dahdi
asterisk13-doc
asterisk13-flite
asterisk13-odbc
asterisk13-ogg
asterisk13-resample
asterisk13-voicemail
at
attr
audit
audit-libs
authconfig
autogen-libopts
avahi
avahi-libs
basesystem
bash
bc
bind-libs
bind-libs-lite
bind-license
bind-utils
binutils
biosdevname
bluez-libs
boost-filesystem
boost-program-options
boost-system
boost-thread
btrfs-progs
bzip2-libs
c-ares
ca-certificates
cairo
centos-indexhtml
chkconfig
chrony
copy-jdk-configs
coreutils
cpio
cpp
cracklib
cracklib-dicts
crda
cronie
cronie-noanacron
crontabs
cryptsetup
cryptsetup-libs
cups-libs
curl
cyrus-sasl-lib
cyrus-sasl-plain
dahdi-firmware
dahdi-linux
dahdi-tools
dbus
dbus-glib
dbus-libs
dbus-python
deltarpm
device-mapper
device-mapper-event
device-mapper-event-libs
device-mapper-libs
device-mapper-multipath
device-mapper-multipath-libs
device-mapper-persistent-data
dhclient
dhcp-common
dhcp-libs
diffutils
dmidecode
dmraid
dmraid-events
dnsmasq
dos2unix
dosfstools
dracut
dracut-network
e2fsprogs
e2fsprogs-libs
easyrsa3
ebtables
ed
efibootmgr
efivar-libs
elfutils-default-yama-scope
elfutils-libelf
elfutils-libs
ethtool
expat
fail2ban-fpbx
fcoe-utils
ffmpeg
ffmpeg-libs
file
file-libs
filesystem
findutils
fipscheck
fipscheck-lib
firewalld
firewalld-filesystem
flac-libs
flite
fontconfig
fontpackages-filesystem
freepbx
freeradius
freetype
fribidi
ftp
fuse
fuse-libs
gamin
gamin-python
gawk
gcc
gcc-c++
gdbm
gdk-pixbuf2
gettext
gettext-libs
gfs2-utils
ghostscript
ghostscript-fonts
giflib
git
glib2
glibc
glibc-common
glibc-devel
glibc-headers
glibmm24
gmp
gnupg2
gnutls
gobject-introspection
gperftools-libs
gpgme
gpm-libs
graphite2
grep
groff-base
grub2
grub2-common
grub2-efi-x64
grub2-pc
grub2-pc-modules
grub2-tools
grub2-tools-efi
grub2-tools-extra
grub2-tools-minimal
grubby
gsm
gzip
hardlink
harfbuzz
hostname
htop
httpd
httpd-tools
hwdata
icu
iksemel
ilmbase
incron
info
initscripts
iproute
iprutils
ipset
ipset-libs
iptables
iptables-services
iputils
irqbalance
iscsi-initiator-utils
iscsi-initiator-utils-iscsiuio
iw
iwl100-firmware
iwl1000-firmware
iwl105-firmware
iwl135-firmware
iwl2000-firmware
iwl2030-firmware
iwl3160-firmware
iwl3945-firmware
iwl4965-firmware
iwl5000-firmware
iwl5150-firmware
iwl6000-firmware
iwl6000g2a-firmware
iwl6000g2b-firmware
iwl6050-firmware
iwl7260-firmware
iwl7265-firmware
jack-audio-connection-kit
jansson
jasper-libs
java-1.8.0-openjdk
java-1.8.0-openjdk-headless
javapackages-tools
jbigkit-libs
json-c
kbd
kbd-legacy
kbd-misc
kernel
kernel
kernel-headers
kexec-tools
keyutils-libs
kmod
kmod-cciss
kmod-dahdi-linux
kmod-forcedeth
kmod-libs
kmod-via-rhine
kmod-via-velocity
kmod-wanpipe
kpartx
krb5-libs
lame
lame-libs
lcms2
less
libICE
libSM
libX11
libX11-common
libXau
libXcomposite
libXdamage
libXext
libXfixes
libXfont
libXft
libXi
libXpm
libXrender
libXt
libXtst
libXv
libXxf86vm
libacl
libaio
libao
libass
libassuan
libasyncns
libattr
libavdevice
libblkid
libcap
libcap-ng
libcdio
libcdio-paranoia
libcom_err
libconfig
libcroco
libcurl
libdaemon
libdb
libdb-utils
libdc1394
libdnet
libdrm
libedit
libestr
libevent
libfastjson
libffado
libffi
libfontenc
libgcc
libgcrypt
libgnome-keyring
libgomp
libgpg-error
libical
libicu
libicu-devel
libidn
libiec61883
libjpeg-turbo
libmnl
libmodman
libmount
libmpc
libmpg123
libmspack
libnetfilter_conntrack
libnfnetlink
libnl
libnl3
libogg
libopenr2
libpcap
libpciaccess
libpipeline
libpng
libpri
libproxy
libpwquality
librados2
libraw1394
libreport-filesystem
libresample
librsvg2
libsamplerate
libseccomp
libselinux
libselinux-python
libselinux-utils
libsemanage
libsepol
libsigc++20
libsmi
libsndfile
libsrtp
libss
libss7
libssh2
libstdc++
libstdc++-devel
libstemmer
libtalloc
libtasn1
libthai
libtheora
libtiff
libtiff-tools
libtirpc
libtonezone
libtool-ltdl
libunistring
libunwind
libusb
libusbx
libuser
libutempter
libuuid
libv4l
libvdpau
libverto
libvorbis
libwat
libwmf-lite
libxcb
libxml++
libxml2
libxml2-python
libxshmfence
libxslt
linux-firmware
lksctp-tools
lldpad
lm_sensors
lm_sensors-libs
log4cxx
logrotate
lsof
lsscsi
lua
lvm2
lvm2-libs
lyx-fonts
lzo
mailcap
mailx
make
man-db
mariadb
mariadb-libs
mariadb-server
mdadm
mesa-libEGL
mesa-libGL
mesa-libgbm
mesa-libglapi
mlocate
mod_ssl
mokutil
mongodb-server
mosh
mozjs17
mpfr
mpg123
mysql-connector-odbc
nano
ncurses
ncurses-base
ncurses-libs
neon
net-tools
nettle
newt
newt-python
nmap
nmap-ncat
nodejs
nspr
nss
nss-pem
nss-softokn
nss-softokn-freebl
nss-sysinit
nss-tools
nss-util
ntp
ntpdate
ntsysv
numactl-libs
open-vm-tools
openal-soft
opencv-core
openjpeg-libs
openldap
openssh
openssh-clients
openssh-server
openssl
openssl-libs
openvpn
opus
orc
os-prober
p11-kit
p11-kit-trust
pakchois
pam
pango
parted
passwd
pciutils
pciutils-libs
pcre
perl
perl-Carp
perl-Compress-Raw-Bzip2
perl-Compress-Raw-Zlib
perl-DBD-MySQL
perl-DBI
perl-Data-Dumper
perl-Encode
perl-Error
perl-Exporter
perl-File-Path
perl-File-Temp
perl-Filter
perl-Getopt-Long
perl-Git
perl-HTTP-Tiny
perl-IO-Compress
perl-IO-Socket-INET6
perl-Net-Daemon
perl-PathTools
perl-PlRPC
perl-Pod-Escapes
perl-Pod-Perldoc
perl-Pod-Simple
perl-Pod-Usage
perl-Scalar-List-Utils
perl-Socket
perl-Socket6
perl-Storable
perl-TermReadKey
perl-Text-ParseWords
perl-Time-HiRes
perl-Time-Local
perl-constant
perl-libs
perl-macros
perl-parent
perl-podlators
perl-threads
perl-threads-shared
php-digium_register
php56w
php56w-bcmath
php56w-cli
php56w-common
php56w-gd
php56w-intl
php56w-ldap
php56w-mbstring
php56w-mysqlnd
php56w-odbc
php56w-pdo
php56w-pear
php56w-pecl-ssh2
php56w-process
php56w-soap
php56w-xml
pinentry
pixman
pkcs11-helper
pkgconfig
plymouth
plymouth-core-libs
plymouth-scripts
policycoreutils
polkit
polkit-pkla-compat
poppler-data
popt
portaudio
postfix
procps-ng
protobuf
psacct
psmisc
pth
pulseaudio-libs
pygpgme
pyliblzma
python
python-backports
python-backports-ssl_match_hostname
python-chardet
python-configobj
python-decorator
python-firewall
python-gobject-base
python-iniparse
python-javapackages
python-kitchen
python-libs
python-linux-procfs
python-lxml
python-perf
python-pycurl
python-pyudev
python-schedutils
python-setuptools
python-slip
python-slip-dbus
python-urlgrabber
python2-pip
pyxattr
qrencode-libs
quota
quota-nls
radiusclient-ng
readline
rootfiles
rpcbind
rpm
rpm-build-libs
rpm-libs
rpm-python
rsync
rsyslog
sangoma-logos
sangoma-pbx
sangoma-release
schroedinger
screen
sed
selinux-policy
selinux-policy-targeted
setserial
setup
sgpio
shadow-utils
shared-mime-info
shim-x64
slang
snappy
sngrep
sox
soxr
spandsp
speex
sqlite
sqlite2
sudo
sysadmin
sysstat
system-config-firewall-base
system-config-keyboard
system-config-keyboard-base
systemd
systemd-libs
systemd-sysv
sysvinit-tools
t1lib
tar
tcp_wrappers
tcp_wrappers-libs
tcpdump
telnet
tftp-server
tmpwatch
tmux
tncfhh
tncfhh-libs
tncfhh-utils
traceroute
trousers
ttmkfdir
tuned
tzdata
tzdata-java
unixODBC
unzip
urw-fonts
usb_modeswitch
usb_modeswitch-data
usbutils
ustr
util-linux
v8
vim-common
vim-enhanced
vim-filesystem
vim-minimal
virt-what
vsftpd
wanpipe
wavpack
wget
which
whois
wireless-tools
wireshark
wpa_supplicant
xerces-c
xfsprogs
xinetd
xmlsec1
xmlsec1-openssl
xorg-x11-font-utils
xorg-x11-fonts-Type1
xz
xz-libs
yaml-cpp
yum
yum-metadata-parser
yum-plugin-fastestmirror
yum-plugin-versionlock
yum-utils
zend-guard-loader
zip
zlib
::::::::::::::

yum clean all
yum -y upgrade

# remove php to avoid conflicts
yum -y erase php php-cli php-common php-mbstring php-mysql php-pdo php-pear php-process php-xml

yum -y install $ALL

fwconsole ma download sysadmin
fwconsole ma install sysadmin
