#!/bin/sh
# Install FreePBX  - based somewhat on:  
# http://wiki.freepbx.org/display/HTGS/Installing+FreePBX+on+Centos+6.3

[ `whoami` != 'root' ] && exec sudo $0
[ ! -d /usr/src ] && mkdir -p /usr/src
cd /usr/src

yum -y update

if [ "`cat /etc/redhat-release`" != "CentOS release 6.4 (Final)" ]
then
    echo "ERROR: Wrong version of CentOS - please update"
    exit 1
fi

yum -y groupinstall core
yum -y groupinstall base

yum -y install gcc gcc-c++ bison mysql-devel mysql-server php php-mysql php-pear php-mbstring tftp-server httpd make ncurses-devel libtermcap-devel sendmail sendmail-cf caching-nameserver sox newt-devel libxml2-devel libtiff-devel audiofile-devel gtk2-devel subversion kernel-devel git subversion kernel-devel php-process

pear install db

# skipping GV depenencies as it's obsolete

# skipping DAHDI as this is targetting a virtual server

# install asterisk (let caller pick version)
$(eval echo ~${USER})/bin/ba -i || exit 1

# install extra sounds
wget -O - http://downloads.asterisk.org/pub/telephony/sounds/asterisk-extra-sounds-en-gsm-current.tar.gz | tar xvfz - --directory=/var/lib/asterisk/sounds

# get FreePBX
export VER_FREEPBX=2.11
svn co http://www.freepbx.org/v2/svn/freepbx/branches/${VER_FREEPBX} freepbx
cd freepbx

[ -z "`grep '^asterisk:' /etc/passwd`" ] && adduser asterisk -M -c "Asterisk User"
chown asterisk. /var/run/asterisk
chown -R asterisk. /etc/asterisk
chown -R asterisk. /var/{lib,log,spool}/asterisk
chown -R asterisk. /usr/lib/asterisk
[ ! -d /var/www/html ] && mkdir /var/www/html
chown -R asterisk. /var/www

sed -i 's/\(^upload_max_filesize =\).*/\120M/' /etc/php.ini
sed -i 's/^\(User\|Group\).*/\1 asterisk/' /etc/httpd/conf/httpd.conf
service httpd restart
service mysqld restart
chkconfig httpd on
chkconfig mysqld on

export ASTERISK_DB_PW=amp109
mysqladmin -u root create asterisk
mysqladmin -u root create asteriskcdrdb
mysql -u root asterisk < SQL/newinstall.sql
mysql -u root asteriskcdrdb < SQL/cdr_mysql_table.sql

mysql -u root -e "GRANT ALL PRIVILEGES ON asterisk.* to asteriskuser@localhost IDENTIFIED BY '${ASTERISK_DB_PW}';"
mysql -u root -e "GRANT ALL PRIVILEGES ON asteriskcdrdb.* to asteriskuser@localhost IDENTIFIED BY '${ASTERISK_DB_PW}';"
mysql -u root -e "flush privileges;"

./start_asterisk start
./install_amp --my-svn-is-correct || ./install_amp --my-svn-is-correct --username=asteriskuser --password=$ASTERISK_DB_PW
amportal a ma installall 
amportal a reload

ln -s /var/lib/asterisk/moh /var/lib/asterisk/mohmp3
amportal start


