#!/bin/sh
# run asterisk testsuite
set -ex
# don't presume that PATH includes ~/bin (mock-erdization)
export PATH="~/bin:$PATH"

ba -i trunk
ba testsuite
cd testsuite
pwd ; ls ; echo $PATH
./runtests.py
Mail -s "TESTSUITE RESULTS" sgriepentrog@digium.com < asterisk-test-suite-report.xml
