#!/bin/sh
# pre-build asterisk - install base packages needed for building Asterisk
[ `whoami` != 'root' ] && sudo $0 && exit

# assuming CentOS for now
# NOTE: May need to install EPEL!
yum -y install php make wget openssl-devel ncurses-devel newt-devel libxml2-devel kernel-devel gcc gcc-c++ sqlite-devel libuuid-devel gtk2-devel gmime-devel

# if libjansson not installed...
if [ ! -f /usr/local/lib/libjansson.so.4 ]
then
	wget -O /tmp/jansson-2.4.tar.gz http://www.digip.org/jansson/releases/jansson-2.4.tar.gz
	tar xvfz /tmp/jansson-2.4.tar.gz --no-same-owner
	(cd jansson-2.4; ./configure && make && sudo make install)
fi

if [ -d /usr/lib64 ]
then
	sudo cp /usr/local/lib/libjansson.so.4 /usr/lib64
fi
