#!/bin/sh
# use a mock shell to run asterisk testsuite
set -ex

MOCK="epel-7-x86_64"

[ `uname -m` != "x86_64" ] && echo "Error: CentOS 7 requires x86_64" && exit 1
install-packages mock

[ ! -f /etc/mock/$MOCK.cfg ] && echo "Error: did not find $MOCK.cfg in /etc/mock, maybe udpate mock?" && exit 1

grep "^mock:.*$USER" /etc/group || sudo usermod -a -G mock $USER

mock -r $MOCK --clean
mock -r $MOCK --init
mock -r $MOCK --install yum git sudo
mock -r $MOCK --chroot "cd ; git clone https://github.com/stgnet/bin"
mock -r $MOCK --chroot "sed -i -e 's/ requiretty/!requiretty/' /etc/sudoers"
mock -r $MOCK --chroot "~/bin/mock-asterisk-test"
Mail -s "Asterisk Test Results" sgriepentrog@digium.com < /var/lib/mock/$MOCK/root/testsuite/asterisk-test-suite-report.xml
