#!/bin/sh
# Install EPEL for this version
[ `whoami` != 'root' ] && exec sudo $0

[ ! -f /etc/redhat-release ] && echo "ERROR: not a RedHat/Fedora/CentOS system" && exit

RHVER="`cat /etc/redhat-release`"

VERSION="${RHVER#* release }"
VERSION="${VERSION%.*}"

RPM=""
[ "$VERSION" = "7.0" ] && RPM="elrepo-release-7.0-2.el7.elrepo.noarch.rpm"
[ "$VERSION" = "6" ] && RPM="elrepo-release-6-5.el6.elrepo.noarch.rpm"
[ "$VERSION" = "5" ] && RPM="elrepo-release-5-4.el6.elrepo.noarch.rpm"

PLATFORM="`uname -m`"
[ "$PLATFORM" = "i686" ] && PLATFORM="x86_64"
[ "$PLATFORM" = "i586" ] && PLATFORM="i386"

URL="http://elrepo.org"

rpm --import http://elrepo.org/RPM-GPG-KEY-elrepo.org

rpm -Uvh $URL/$RPM

