#!/bin/sh
# Install RPMFORGE for this version

[ ! -f /etc/redhat-release ] && echo "ERROR: not a RedHat/Fedora/CentOS system" && exit

RHVER="`cat /etc/redhat-release`"

VERSION=""
[ "$RHVER" = "CentOS release 6.3 (Final)" ] && VERSION="6"
[ "$RHVER" = "CentOS release 6.4 (Final)" ] && VERSION="6"

[ -z "$VERSION" ] && echo "ERROR: version not implemented in script - please fix:" && echo $RHVER && exit

RPM=""
[ "$VERSION" = "6" ] && RPM="rpmforge-release-0.5.2-2.el6.rf"

PLATFORM="`uname -m`"

BASE="http://packages.sw.be/rpmforge-release"

rpm --import http://apt.sw.be/RPM-GPG-KEY.dag.txt
rpm -Uvh $BASE/$RPM.$PLATFORM.rpm
yum -y update rpmforge-release
