#!/bin/sh
# Install EPEL for this version
[ `whoami` != 'root' ] && exec sudo $0

[ ! -f /etc/redhat-release ] && echo "ERROR: not a RedHat/Fedora/CentOS system" && exit 1
[ -f /etc/yum.repos.d/epel.repo ] && echo "Not an error: EPEL is already installed" && exit 0

yum -y install epel-release

